### ISSUE TITLE
Does this lib also take care of hotspot?

### ISSUE THREAD

**Issue by zRelux** [lorenzodejong/next-sanity-image#32]
I was wondering if this library does take care of focal points

**Comment by danieljb** [comment]
Hi @zRelux, as far as I understand this library does not respect Sanity’s hotspot feature.

A quick workaround is to set `objectPosition` calculated from Sanity’s image data:

```jsx
import Img from "next/image";
import { useNextSanityImage } from "next-sanity-image";

// untested
function ImageComponent({ image }) {
  /*
    {
      "_type": "image",
      "asset": {
        "_ref": "image-[…]-jpg",
        "_type": "reference"
      },
      "crop": {
        "_type": "sanity.imageCrop",
        "bottom": 0,
        "left": 0,
        "right": 0,
        "top": 0
      },
      "hotspot": {
        "_type": "sanity.imageHotspot",
        "height": 0.07233187772925773,
        "width": 0.07423580786026142,
        "x": 0.5611353711790394,
        "y": 0.7135109170305682
      }
    }
  */
  const imageProps = useNextSanityImage(client, image);

  const attributes = {};
  if (image.hotspot?.x && image.hotspot?.y) {
    const { x, y } = image.hotspot;
    attributes.objectPosition = `${x * 100}% ${y * 100}%`;
  }
  return (
    <Image {...imageProps} {...attributes} />
  );
}
```

This only works in certain `layout` and `objectFit` combinations and depends on CSS styling (e.g. whether the image component is constraint to an aspect ratio). Note, this does not take the hotspot ellipse (`width` and `height` attributes) into account.

I tried to use a custom url builder to apply image transformations as [described in the README](https://github.com/bundlesandbatches/next-sanity-image#image-transformations) but that did not work without manually passing in `fit=crop&crop=focalpoint&fp-x=${image.hotspot.x}&fp-y=${image.hotspot.y}` and disregards the hotspot ellipse, too.
There also seems to be [a bug #24](https://github.com/sanity-io/image-url/issues/24) pending in Sanity’s image-url.

**Comment by lorenzodejong** [comment]
I think we're not able to implement any standard way of implementing hotspot behavior. Specifically since the styling solution you choose (CSS-in-JS, styled components, something else) determines the way you would want to provide the `objectPosition` styles as described by @danieljb. I would say use the custom `ImageComponent` as provided in his example, aligning with your personal styling solution.

Another potential solution would be to wrap `useNextSanityImage` in a [custom hook](https://reactjs.org/docs/hooks-custom.html).
